[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.104.3"

[context.deploy-preview]
command = "npm run build:preview -- -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_ENV = "staging"
HUGO_VERSION = "0.104.3"

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
       default-src 'self';
       frame-src 'self' edu.chainguard.dev /rumble/ /js/rumble.js https://www.googletagmanager.com https://player.vimeo.com https://www.youtube.com https://www.youtube-nocookie.com https://platform.twitter.com https://syndication.twitter.com https://visualization-ui.chainguard.app https://terminal.inky.wtf https://app.qualified.com;
       style-src 'self' edu.chainguard.dev 'unsafe-inline' cdn.jsdelivr.net https://fonts.googleapis.com https://unpkg.com https://www.googletagmanager.com https://tagmanager.google.com https://googletagmanager.com;
       form-action 'self';
       font-src 'self' edu.chainguard.dev https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.jsdelivr.net;
       script-src 'self' edu.chainguard.dev 'unsafe-inline' 'unsafe-eval' https://www.google.com *.googleapis.com cdn.jsdelivr.net *.netlify.app https://www.googletagmanager.com https://tagmanager.google.com https://googletagmanager.com *.googletagmanager.com https://www.google-analytics.com https://analytics.google.com https://snap.licdn.com https://csp.withgoogle.com https://play.google.com https://www.redditstatic.com http://js.hs-scripts.com https://tag.clearbitscripts.com https://j.6sc.co https://tracking.g2crowd.com https:/tag.unifyintent.com https://static.reo.dev https://googleads.g.doubleclick.net https://js.qualified.com https://js.hscollectedforms.net https://js.hubspot.com https://js.hsadspixel.net https://js.hs-banner.com https://js.hs-analytics.net https://x.clearbitjs.com https://js.zi-scripts.com https://cdn.amplitude.com;
       connect-src 'self' https://www.google.com https://stats.g.doubleclick.net https://www.googletagmanager.com https://tagmanager.google.com https://googletagmanager.com *.google-analytics.com *.googletagmanager.com https://analytics.google.com https://region1.google-analytics.com https://www.google-analytics.com https://px.ads.linkedin.com https://px4.ads.linkedin.com https://storage.googleapis.com https://packages.wolfi.dev https://script.google.com https://script.googleusercontent.com https://csp.withgoogle.com https://play.google.com *.googleapis.com https://api.unifyintent.com https://api.reo.dev https://pixel-config.reddit.com https://www.redditstatic.com https://conversions-config.reddit.com https://ipv6.6sc.co https://static.hsappstatic.net https://app.qualified.com wss://ws6.qualified.com https://api.hubapi.com https://app.clearbit.com https://forms.hscollectedforms.net https://cta-service-cms2.hubspot.com https://js.zi-scripts.com https://ws.zoominfo.com https://x.clearbitjs.com https://js.hs-banner.com https://api2.amplitude.com https://api.amplitude.com;
       img-src 'self' 'unsafe-inline' https://ssl.gstatic.com *.chainguard.dev storage.googleapis.com https://www.googletagmanager.com https://googletagmanager.com https://www.google-analytics.com https://analytics.google.com https://px.ads.linkedin.com https://px4.ads.linkedin.com data: https://alb.reddit.com http://b.6sc.co https://forms.hsforms.com https://perf-na1.hsforms.com https://track.hubspot.com;
       worker-src 'self' blob:;
       base-uri 'self';
    '''


