[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.104.3"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_ENV = "staging"
HUGO_VERSION = "0.104.3"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
       default-src 'self';
       frame-src 'self' edu.chainguard.dev /rumble/ /js/rumble.js https://player.vimeo.com https://www.youtube.com https://www.youtube-nocookie.com https://platform.twitter.com https://syndication.twitter.com https://visualization-ui.chainguard.app https://terminal.inky.wtf;
       style-src 'self' edu.chainguard.dev 'unsafe-inline' cdn.jsdelivr.net https://fonts.googleapis.com https://unpkg.com;
       form-action 'self';
       font-src 'self' edu.chainguard.dev https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.jsdelivr.net;
       script-src 'self' edu.chainguard.dev 'unsafe-inline' *.googleapis.com cdn.jsdelivr.net *.netlify.app *.googletagmanager.com;
       connect-src 'self' edu.google-analytics.com; *.google-analytics.com *.googleapis.com;
       img-src 'self' edu.chainguard.dev data:;
       base-uri 'self';
    '''


