[[docs]]
  name = "Chainguard"
  identifier = "chainguard"
  url = "/chainguard/"
  weight = 10

[[docs]]
  name = "Open Source"
  identifier = "open-source"
  url = "/open-source/"
  weight = 20

[[docs]]
  name = "Compliance"
  identifier = "compliance"
  url = "/compliance/"
  weight = 30

[[docs]]
  name = "Software Security"
  identifier = "security"
  url = "/software-security/"
  weight = 40

[[main]]
  name = "Product Docs"
  identifier = "menu-chainguard"
  weight = 10

[[main]]
  name = "Open Source"
  identifier = "menu-oss"
  weight = 20

[[main]]
  name = "Compliance"
  identifier = "menu-compliance"
  weight = 30

[[main]]
  name = "API Reference"
  url = "/chainguard/api/"
  parent = "menu-chainguard"
  weight = 10

[[main]]
  name = "Chainguard Containers"
  identifier = "chainguard-images"
  url = "/chainguard/chainguard-images/"
  parent = "menu-chainguard"
  weight = 15

[[main]]
  name = "chainctl"
  url = "/chainguard/chainctl/"
  parent = "menu-chainguard"
  weight = 20

[[main]]
  name = "Network Requirements"
  url = "/chainguard/network-requirements/"
  parent = "menu-chainguard"
  weight = 25

[[main]]
  name = "Sigstore"
  url = "/open-source/sigstore/"
  parent = "menu-oss"
  weight = 10

[[main]]
  name = "Wolfi"
  url = "/open-source/wolfi/"
  parent = "menu-oss"
  weight = 15

[[main]]
  name = "apko"
  url = "/open-source/apko/"
  parent = "menu-oss"
  weight = 20

[[main]]
  name = "melange"
  url = "/open-source/melange/"
  parent = "menu-oss"
  weight = 30

[[main]]
  name = "Open Containers"
  url = "/open-source/oci/"
  parent = "menu-oss"
  weight = 35  

[[main]]
  name = "SBOMs"
  url = "/open-source/sbom/"
  parent = "menu-oss"
  weight = 40

[[main]]
  name = "SLSA"
  url = "/compliance/slsa/"
  parent = "menu-compliance"
  weight = 40

[[main]]
  name = "CMMC"
  url = "/compliance/cmmc-2/"
  parent = "menu-compliance"
  weight = 20

[[main]]
  name = "PCI DSS"
  url = "/compliance/pci-dss-4/"
  parent = "menu-compliance"
  weight = 30

[[main]]
  name = "Software Security"
  identifier = "menu-security"
  weight = 20

[[main]]
  name = "Glossary"
  url = "/software-security/glossary/"
  parent = "menu-security"
  weight = 30

[[main]]
  name = "Videos"
  url = "/software-security/videos/"
  parent = "menu-security"
  weight = 40

[[main]]
  name = "What is Software Supply Chain Security"
  url = "/software-security/what-is-software-supply-chain-security/"
  parent = "menu-security"
  weight = 20
  
[[main]]
  name = "How to Select a Secure Base Image"
  url = "/software-security/selecting-a-base-image/"
  parent = "menu-security"
  weight = 25


[[social]]
  name = "X"
  url = "https://twitter.com/chainguard_dev?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 10
  [social.params]
    icon = "x.svg"        

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/chainguard-dev?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 20
  [social.params]
    icon = "linkedin.svg"

[[social]]
  name = "YouTube"
  url = "https://www.youtube.com/channel/UCJYCfj6ZMdyeinWMm_yxwaA?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 30
  [social.params]
    icon = "youtube.svg"  

[[social]]
  name = "GitHub"
  url = "https://github.com/chainguard-dev?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 40
  [social.params]
      icon = "github.svg"

[[footer]]
  name = "Product"
  weight = 1
  identifier = "products"

[[footer]]
  name = "Chainguard Containers"
  url = "https://www.chainguard.dev/containers?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 1
  parent = "products"

[[footer]]
  name = "Chainguard Libraries"
  url = "https://www.chainguard.dev/libraries?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 2
  parent = "products"

[[footer]]
  name = "Chainguard VMs"
  url = "https://www.chainguard.dev/vms?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 3
  parent = "products"

[[footer]]
  name = "Images Directory"
  url = "https://images.chainguard.dev/?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 4
  parent = "products"

[[footer]]
  name = "Integrations"
  url = "https://www.chainguard.dev/scanners?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 5
  parent = "products"

[[footer]]
  name = "Pricing"
  url = "https://www.chainguard.dev/pricing?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 6
  parent = "products"

[[footer]]
  name = "Solutions"
  weight = 2
  identifier = "solutions"

[[footer]]
  name = "FedRAMP"
  url = "https://www.chainguard.dev/solutions/fedramp?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 1
  parent = "solutions"

[[footer]]
  name = "PCI DSS"
  url = "https://www.chainguard.dev/solutions/pci?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 2
  parent = "solutions"

[[footer]]
  name = "CMMC 2.0"
  url = "https://www.chainguard.dev/solutions/cmmc?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 3
  parent = "solutions"


[[footer]]
  name = "Golden Images"
  url = "https://chainguard.dev/solutions/golden-images?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 4
  parent = "solutions"

[[footer]]
  name = "CVE Remediation"
  url = "https://www.chainguard.dev/solutions/cve-remediation?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 5
  parent = "solutions"

[[footer]]
  name = "Public Sector"
  url = "https://www.chainguard.dev/solutions/public-sector?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 6
  parent = "solutions"

[[footer]]
  name = "Customers"
  weight = 3
  identifier = "customers"

[[footer]]
  name = "Customer Stories"
  url = "https://chainguard.dev/customers?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 1
  parent = "customers"

[[footer]]
  name = "Chainguard Reviews"
  url = "https://www.chainguard.dev/chainguard-love?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 2
  parent = "customers"


[[footer]]
  name = "Company"
  weight = 5
  identifier = "company"

[[footer]]
  name = "About Us"
  url = "https://chainguard.dev/about-us?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 1
  parent = "company"

[[footer]]
  name = "Blog"
  url = "https://chainguard.dev/unchained?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 2
  parent = "company"

[[footer]]
  name = "Partners"
  url = "https://www.chainguard.dev/partners?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 3
  parent = "company"

[[footer]]
  name = "Newsroom"
  url = "https://chainguard.dev/newsroom?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 4
  parent = "company"

[[footer]]
  name = "Careers"
  url = "https://chainguard.dev/careers?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 5
  parent = "company"

[[footer]]
  name = "Legal"
  url = "https://www.chainguard.dev/legal?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 6
  parent = "company"


[[footer]]
  name = "Resources"
  weight = 4
  identifier = "resources"

[[footer]]
  name = "Events & Webinars"
  url = "https://chainguard.dev/events?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 1
  parent = "resources"

[[footer]]
  name = "Chainguard Courses"
  url = "https://courses.chainguard.dev/?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 2
  parent = "resources"

[[footer]]
  name = "Documentation"
  url = "/"
  weight = 3
  parent = "resources"

[[footer]]
  name = "Trust Center"
  url = "https://security.chainguard.dev/?utm_source=cg-academy&utm_medium=referral&utm_campaign=dev-enablement"
  weight = 4
  parent = "resources"
