name: Rumble Vulnerability Data
on:
  schedule:
    - cron: "1 5 * * *"
  workflow_dispatch:
  push:
    branches: [rumble-insights]

env:
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash
    working-directory: ./tools/rumble

permissions: {}

jobs:
  generate-csvs-and-json:
    runs-on: ubuntu-latest

    if: github.repository == 'chainguard-dev/edu'

    permissions:
      contents: read
      id-token: write # federate with GCP

    steps:
      - name: 'Github Actions Runner'
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: 'Checkout default branch to $GITHUB_WORKSPACE dir'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: ./tools/rumble/go.mod
          check-latest: true

      - name: Authenticate to Google Cloud
        id: auth
        uses: step-security/google-github-auth@40f6deebd366f16c782d7a0ad0844e3b96a032a6 # v2.1.10
        with:
          service_account: "github-chainguard-academy@chainguard-academy.iam.gserviceaccount.com"
          workload_identity_provider: "projects/456977358484/locations/global/workloadIdentityPools/chainguard-academy/providers/chainguard-edu"

      - name: Generate vulnerability JSON files
        run: |
          go run main.go vulns \
            --project prod-enforce-fabc \
            --db cloudevents_grype_scan_results \
            --gcs-project chainguard-academy \
            --bucket chainguard-academy \
            --upload

      - name: Generate image comparison CSVs
        run: |
          go run main.go image-csv \
            --project prod-enforce-fabc \
            --db cloudevents_grype_scan_results \
            --gcs-project chainguard-academy \
            --bucket chainguard-academy \
            --rumble-json-path ../../data/rumble.json \
            --upload

      - name: Generate legacy comparison CSV
        run: |
          go run main.go legacy-csv \
            --project prod-enforce-fabc \
            --db cloudevents_grype_scan_results \
            --gcs-project chainguard-academy \
            --bucket chainguard-academy \
            --upload

      - name: Post failure notice to Slack
        uses: step-security/action-slack-notify@cafbebd7b2b3e2f62d6a3cebac172962e7f55c05 # v2.3.4
        if: ${{ failure() }}
        env:
          SLACK_ICON: http://github.com/chainguard-dev.png?size=48
          SLACK_USERNAME: guardian
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'alerts-edu'
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: 'Rumble vuln data failed - ${{ github.repository }}'
          SLACK_MESSAGE: |
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
